vm.swappiness=150
vm.max_map_count=2147483642
net.core.rmem_max=16777216
net.core.wmem_max=16777216
vm.compaction_proactiveness=0
vm.page_lock_unfairness=1
fs.inotify.max_user_instances=512
# hide kernel symbol addresses from unprivileged users
kernel.kptr_restrict=1
# drop packets with impossible source addresses (anti-spoofing)
net.ipv4.conf.all.rp_filter=1
net.ipv4.conf.default.rp_filter=1
